# This workflow will upload a Python Package using pypa/gh-action-pypi-publish when a release is created
name: Upload Python Package
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Build distribution
        run: make dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
